# Configuration of Hugo
# Guide: https://docs.hugoblox.com/tutorial/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Website name
title: Yujuan Wang
baseurl: 'https://yjwang39.github.io/'



############################
## LANGUAGE
############################

defaultContentLanguage: en
hasCJKLanguage: true
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## ADVANCED
############################
proxy: https://goproxy.cn
build:
  writeStats: true
enableGitInfo: true
summaryLength: 30
pagination.pagerSize: 5
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
disableAliases: true


permalinks:
  tags: '/tag/:slug/'
  categories: '/category/:slug/'
  publication_types: '/publication-type/:slug/'

outputs:
  home: [HTML, RSS, headers, redirects, backlinks]
  section: [HTML, RSS]

imaging:
  resampleFilter: lanczos
  quality: 80
  anchor: smart

timeout: 600000

taxonomies:
  author: authors
  tag: tags
  publication_type: publication_types

markup:
  _merge: deep
  highlight:
    lineNos: false

related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100

security:
  _merge: deep

sitemap:
  _merge: deep

minify:
  _merge: deep

cascade:
  - _target:
      path: /**
    pager: true
    editable: true
    reading_time: true
    commentable: true
    show_related: false
    show_breadcrumb: true
    share: true

