# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '/'
    weight: 10
  - name: Publications
    url: 'publication'
    weight: 30
  - name: Presentations
    url: 'talk'
    weight: 40
  - name: Research
    url: 'project'
    weight: 45
  - name: CV
    url: uploads/cv.pdf
    weight: 50
  - name: Contact
    url: '/#contact'
    weight: 60

    